# Generated by Django 5.0.6 on 2024-06-01 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petinfo', '0001_initial'),
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.shelter'),
        ),
    ]
