# Generated by Django 5.0.6 on 2024-06-05 06:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petinfo', '0002_alter_pet_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
